import = [
    "~/.config/alacritty/themes/oxocarbon.toml"
]

[env]
TERM = "xterm-256color"

[terminal]
osc52 = "OnlyCopy"

[window]
decorations = "None"
option_as_alt = "Both"

[font]
size = 17.0
normal = { family = "Berkeley Mono", style = "Regular" }
bold = { family = "Berkeley Mono", style = "Bold" }
italic = { family = "Berkeley Mono", style = "Italic" }
