# Edge Light Alacritty Colors
# Default colors
[colors.primary]
background = '#fafafa'
foreground = '#4b505b'

# Cursor colors
[colors.cursor]
cursor = '#4b505b'  # Same as foreground
text = '#fafafa'    # Same as background

# Normal colors
[colors.normal]
black = '#4b505b'
red = '#d05858'
green = '#608e32'
yellow = '#be7e05'
blue = '#5079be'
magenta = '#b05ccc'
cyan = '#3a8b84'
white = '#fafafa'

# Bright colors
[colors.bright]
black = '#4b505b'
red = '#d05858'
green = '#608e32'
yellow = '#be7e05'
blue = '#5079be'
magenta = '#b05ccc'
cyan = '#3a8b84'
white = '#fafafa'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#d05858'

[[colors.indexed_colors]]
index = 17
color = '#b05ccc'
