# Material Palenight Alacritty Colors
# Default colors
[colors.primary]
background = '#292D3E'
foreground = '#A6ACCD'

# Normal colors
[colors.normal]
black = '#292D3E'
red = '#F07178'
green = '#C3E88D'
yellow = '#FFCB6B'
blue = '#82AAFF'
magenta = '#C792EA'
cyan = '#89DDFF'
white = '#D0D0D0'

# Bright colors
[colors.bright]
black = '#434758'
red = '#FF8B92'
green = '#DDFFA7'
yellow = '#FFE585'
blue = '#9CC4FF'
magenta = '#E1ACFF'
cyan = '#A3F7FF'
white = '#FFFFFF'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#F78C6C'

[[colors.indexed_colors]]
index = 17
color = '#FF5370'
